import Neon from "../logos/imgbin_fortnite-battle-royale-skin-battle-royale-game-epic-games-png 3.png"
import Plague from "../logos/Fortnite-Plague-PNG-HD 3.png"
import Flash from "../logos/imgbin_fortnite-battle-royale-tool-playerunknowns-battlegrounds-pickaxe-png 3.png"
import Sniper from "../logos/Fortnite-Weapons-PNG 3.png"
import Rifle from "../logos/Fortnite-Weapons-PNG-Free-Download 3.png"
import Firozi from "../logos/Among-Us-Transparent-PNG 3.png"
import Pistol from "../logos/Fortnite-Weapons-Download-PNG-Image 3.png"
import Batman from "../logos/Batman-Mask-Dark-Knight-PNG 3.png"
import M4S1 from "../logos/pngegg-M4S1.png"
import M4S2 from "../logos/pngegg-M4S2.png"

import binance from "../logos/binance.png"
import ftx from "../logos/ftx.png"
import wazirX from "../logos/wazirX.png"
import steam from "../logos/steam.png"
import openSea from "../logos/openSea.png"
import sugaVerse from "../logos/sugaVerse.png"

import trending from "../logos/trending.png"
import premium from "../logos/premium.png"


export const McardDetails = [
    {
        name: 'Neon Pro Skin',
        image: Neon,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "NFT",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Plague Mask',
        image: Plague,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Flash Axe',
        image: Flash,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "S",
        type1: "null",
    },
    {
        name: 'YHB-10 Smoke Sniper',
        image: Sniper,
        categorieName: "OpenSea",
        categorieLogo: openSea,
        categorieName2: "NFT",
        type: premium,
        type1: "premium",
    },
    {
        name: 'KD52 Silver Assult Rifle ',
        image: Rifle,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Amoung Us Firozi',
        image: Firozi,
        categorieName: "Steam",
        categorieLogo: steam,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Pistol,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
   
    {
        name: 'M4 A1 - S',
        image: M4S2,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Neon Pro Skin',
        image: Neon,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "NFT",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Plague Mask',
        image: Plague,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Flash Axe',
        image: Flash,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "S",
        type1: "null",
    },
    {
        name: 'YHB-10 Smoke Sniper',
        image: Sniper,
        categorieName: "OpenSea",
        categorieLogo: openSea,
        categorieName2: "NFT",
        type: premium,
        type1: "premium",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'KD52 Silver Assult Rifle ',
        image: Rifle,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Amoung Us Firozi',
        image: Firozi,
        categorieName: "Steam",
        categorieLogo: steam,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Pistol,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'M4 A1 - S',
        image: M4S2,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Pistol,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'Neon Pro Skin',
        image: Neon,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "NFT",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Plague Mask',
        image: Plague,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Flash Axe',
        image: Flash,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "S",
        type1: "null",
    },
    {
        name: 'YHB-10 Smoke Sniper',
        image: Sniper,
        categorieName: "OpenSea",
        categorieLogo: openSea,
        categorieName2: "NFT",
        type: premium,
        type1: "premium",
    },
    {
        name: 'KD52 Silver Assult Rifle ',
        image: Rifle,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Amoung Us Firozi',
        image: Firozi,
        categorieName: "Steam",
        categorieLogo: steam,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Pistol,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'M4 A1 - S',
        image: M4S2,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Neon Pro Skin',
        image: Neon,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "NFT",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Plague Mask',
        image: Plague,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Neon Pro Skin',
        image: Neon,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "NFT",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Plague Mask',
        image: Plague,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Flash Axe',
        image: Flash,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "S",
        type1: "null",
    },
    {
        name: 'YHB-10 Smoke Sniper',
        image: Sniper,
        categorieName: "OpenSea",
        categorieLogo: openSea,
        categorieName2: "NFT",
        type: premium,
        type1: "premium",
    },
    {
        name: 'KD52 Silver Assult Rifle ',
        image: Rifle,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Amoung Us Firozi',
        image: Firozi,
        categorieName: "Steam",
        categorieLogo: steam,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Pistol,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'YHB-10 Smoke Sniper',
        image: Sniper,
        categorieName: "OpenSea",
        categorieLogo: openSea,
        categorieName2: "NFT",
        type: premium,
        type1: "premium",
    },
    {
        name: 'KD52 Silver Assult Rifle ',
        image: Rifle,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "Skinm",
        type1: "null",
    },
    {
        name: 'Amoung Us Firozi',
        image: Firozi,
        categorieName: "Steam",
        categorieLogo: steam,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Pistol,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Amoung Us Firozi',
        image: Firozi,
        categorieName: "Steam",
        categorieLogo: steam,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Thassbuddhi Pistol',
        image: Firozi,
        categorieName: "SugaVerse",
        categorieLogo: sugaVerse,
        categorieName2: "S",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Batman Mask',
        image: Batman,
        categorieName: "FTX",
        categorieLogo: ftx,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'M4 A1 - S',
        image: M4S1,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "S",
        type: premium,
        type1: "premium",
    },
    {
        name: 'M4 A1 - S',
        image: M4S2,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "NFT",
        type1: "null",
    },
    {
        name: 'Neon Pro Skin',
        image: Neon,
        categorieName: "Binance",
        categorieLogo: binance,
        categorieName2: "NFT",
        type: trending,
        type1: "trending",
    },
    {
        name: 'Plague Mask',
        image: Plague,
        categorieName: "WazirX",
        categorieLogo: wazirX,
        categorieName2: "Skinm",
        type1: "null",
    },
   
]